### ISSUE TITLE
rework term and separate term management for multiple terms

### ISSUE THREAD

**Issue by payonel** [payonel/OpenComputers#1]
more info/description to come

**Comment by mpmxyz** [comment]
A list of targets:
-allowing creation of term objects that are more or less just streams
-drawing and input of terms is handled somewhere else (core_term/ term manager)

**Comment by payonel** [comment]
So my explanation to think of terms as streams was to help separate the concerns of term and term manager just like io is separate from the shell. Terms are not streams, they are not buffers. Term are just a terminal window; a GUI object that can print text and read keyboard key events (and touch events). A term is bound to a specific gpu just like a gpu can bind to a screen. Writing to a term will write to the screen its gpu is bound to. If in the future we have multiple terms and multiple screens - touch events will have to be filtered to notify only terminals on the gpu of the screen that was hit -- such should not be the concern of the terminal.

Also - a terminal shouldn't have to check if it has focus, rather, a manager should notify whom ever is in focus. This is just something to keep in mind as you build the manager code. Terminals should be dumb.

I gave stdin/out/err more thought - and in general any number of user defined io fds (stdin/out/err are just 1/2/3) and the term is not a representation of these concepts, it (as stated in the first paragraph) represents a console terminal with a specific gpu. gpu+screen relations don't care about stdout vs stderr.

Could stderr go from one term all the way to another term? sure, term relations will be kept in process data, and thus piping stderr (or any io) from one process to another may cross term boundaries. The terms don't know or care.

I'll also try to answer your other questions now -- please note that I'm still working out a lot of these specifics. If you see conflicting problems with my design proposal feel free to point them out.

So first of all, I think the vast majority of your work in term.lua can work as is in a manager library. I don't think your variants of this rework are necessary. Maybe you'll just have to wait and see :)

A term knows it's own cursor state. Your term manager would keep track of a list of terms, where by default the system only has 1 term. So setCursorPos and such would work the same.

**Comment by payonel** [comment]
also, term.getGPU() will just be term.gpu() and return the gpu the term is bound to
why did yours return two args? what was the first supposed to be used for?
nothing in openos uses the first param

**Comment by payonel** [comment]
another thing, boot/93_term.lua will be the right place to open the first default term, but if components become unavailable, the logic could be improved to have the main terminal only go inactive if ITS gpu or screen is lost - something to review later

**Comment by payonel** [comment]
ok the way this is going, i'd really like process data to have the term object, and term api only checks IT for the term

in the real world this makes sense, a single process doesn't just send data to two different terms at will (NORMALLY). normally, a process stays on the same term

Thus, if you want to make it possible for a term to be changed at will on the same process, I think it would be best to change process data, like this
process.info().data.window = term_a
term.write() -- writes to term a
process.info().data.window = term_b
term.write() -- writes to term b

**Comment by payonel** [comment]
@mpmxyz Using latest from my next-term branch, the following code prototype demonstrates multiple terminals running concurrently. It creates 2 terminal windows, one at 5, 10 size 80, 10; the other at 7, 25 size 70, 10. It runs /bin/sh in each. When you start, only the first window will render, ctrl+tab to switch and you'll see the 2nd render. You'll need to run "exit" in the shell to stop the process. When both are dead, you'll return from the test prototype.

A couple of thoughts, programs should not be required to be aware they are running in a multi-term environment. They really should not have to check term hasFocus, nor what keyboard sent the event. Again, this code is a prototype! I am using methods from /lib/pipes.lua that are marked "internal" for a reason, that is, the api is not final, I do not plan on documented all of it, it is subject to change...but, this is how to use it for this purpose - this gives us real multi-process switching.

I also created this prototype using just coroutines, yield and resume. But a process that pulls its own events will disrupt coroutine handling. Using OpenOS 1.6 pipe system (/lib/pipes) as shown in this code can deal with any of that.

`local term = require("term")
local component = require("component")
local process = require("process")
local event = require("event")
local kb = require("keyboard")
local keys = kb.keys
local pipes = require("pipes")

-- 110 test width
-- 50 test height

local function binder(w)
  local gpu = component.gpu
  local screen = component.proxy(gpu.getScreen())
  local kb = component.proxy(screen.getKeyboards()[1])
  term.bind(w, gpu, screen, kb)
end

local function prepareWindow(dx,dy,w,h)
  local w = term.internal.open(component.gpu, dx, dy, w, h)
  binder(w)
  return w
end

local pcos = {}

pcos[1] = pipes.internal.create("/bin/sh.lua")
process.info(pcos[1].stack[1]).data.window = prepareWindow(5, 10, 80, 10)

pcos[2] = pipes.internal.create("/bin/sh.lua")
process.info(pcos[2].stack[1]).data.window = prepareWindow(7, 25, 70, 10)

local current_pco
local keyDownListener
keyDownListener = function(e,addr,char,code)
  if #pcos == 0 then event.ignore("key_down", keyDownListener) end
  if code ~= keys.tab then return end
  if not kb.isControlDown(addr) then return end
  if not current_pco then return end
  local win = term.internal.window()
  if term.keyboard(win).address == addr then
    current_pco.yield_all()
  end
end

event.listen("key_down", keyDownListener)

local index = 0
while #pcos>0 do
  index = index % #pcos
  current_pco = pcos[index+1]
  if not current_pco then
    break
  else
    current_pco.resume_all()
    if not current_pco.top() then
      table.remove(pcos,index+1)
    else
      index = index + 1
    end
  end
end

event.ignore("key_down", keyDownListener)`

**Comment by mpmxyz** [comment]
That looks quite clean.
Unfortunately I'm a bit busy for the next week or even a bit longer. It might take some time until I get started with a "window manager". One thing though: It would be nice if the window manager is able to change gpu/position of a terminal window using some kind of interface function.

**Comment by payonel** [comment]
@mpmxyz I saw your messages in #oc on irc (and I don't know how else to contact you really besides github)

I looked through your code a little bit, and I like the direction you are taking it.

Feel free to ping me here to review and test it. I'm continually making fixes (still) to OpenOS and shell and term as I find issues.
