### ISSUE TITLE
cp -x broken on openos 1.6

### ISSUE THREAD

**Issue by payonel** [payonel/OpenComputers#2]

**Comment by fnuecke** [comment]
Hrm, still getting the ``cannot copy a directory, `mnt', into itself, `/mnt/xxx/mnt'`` when running install, mind looking into that again?

**Comment by payonel** [comment]
I will look at this, I think you have found a good use case that I didn't test. Can you share the exact command you are testing so I make sure I am understanding the bug correctly? Thanks

**Comment by payonel** [comment]
I believe I have the right fix for this. I'm reviewing merges and such.

**Comment by fnuecke** [comment]
I just spawned a new computer (`/oc_sc` command), booted it and ran `install`, `1`.
Who knows, maybe it's just `install` invoking `cp` incorrectly?

**Comment by payonel** [comment]
the current PR fix for cp appears to work correctly, and the install test you gave works, but we have another problem --- cp -xr in real linux will create empty dirs of mounted filesystems, and this gives us duplicate dir names after install in oc. more info to you privately in email
